# ~/das-app/ToFiMi/docker-compose.yml
services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}

  app:
    image: ghcr.io/tofimi/tofimi:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  loki:
    image: grafana/loki:2.9.4
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.4
    restart: unless-stopped
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  grafana:
    image: grafana/grafana:11.0.0
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  mongo:
