version: '3.9'
services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    volumes: [ "mongo:/data/db" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}

  app:
    build: .
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:${MONGO_ROOT_PWD}@mongodb:27017/app?authSource=admin
    depends_on: [ mongodb ]
    ports: [ "3000:3000" ]

  loki:
    image: grafana/loki:2
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports: [ "3100:3100" ]

  promtail:
    image: grafana/promtail:2
    restart: unless-stopped
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  grafana:
    image: grafana/grafana:11
    restart: unless-stopped
    ports: [ "80:3000" ]   # Grafana UI

volumes:
  mongo:
